on: [pull_request]

jobs:
  ApkSizeTracker:
    runs-on: ubuntu-latest
    name: Apk size tracker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: 'Checking out current branch'
        run: |
          git fetch origin test3 
          git checkout origin/test3



      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: Custom action step
        id: apkSize
        uses: zsfVishnu/apk-size-tracker@master
        with:
          flavor: 'debug'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


