on: [pull_request]

jobs:
  ApkSizeTracker:
    runs-on: ubuntu-latest
    name: Apk size tracker
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: Custom action step
        id: apkSize
        uses: zsfVishnu/apk-size-tracker@master
        with:
          flavor: 'debug'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




