on:
  push:
      branches:
        - master

jobs:
  ApkSizeTracker:
    runs-on: ubuntu-latest
    name: Apk size tracker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: Upload action step
        id: apkSize
        uses: zsfVishnu/apk-metric-upload@main
        with:
          flavor: 'debug'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       - run: |

#               echo { \"master_size\" : 50 } > sizeArtifact.json
#       - uses: actions/upload-artifact@v3
#         with:
#           name: sizeArtifact
#           path: sizeArtifact.json
